AWSTemplateFormatVersion: 2010-09-09
Description: "Cloud formation template for security group"
stackfilevar:
    stack-name: test-stack-var-file-demoec2
    stack-file: ./cloudformation/ademoec2.yml
