AWSTemplateFormatVersion: 2010-09-09
Description: "Cloud formation template for security group"
Parameters:
  Environment:
    Description: Environment Name
    Type: String
Resources:
  CTLHTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable port 80 and port 443 test
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
      - CidrIp: 0.0.0.0/0
        FromPort: 443
        IpProtocol: tcp
        ToPort: 443
