name: Cloudformation diff 

on: [push]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run YAML to Github Output Action
      id: yaml-output
      uses: christian-ci/action-yaml-github-output@v2
      with:
        file_path: ./cloudformation/stack-var.yml
        main_key: stackfilevar

    - name: Print Variables
      run: |
        echo "Stack Name: ${{ env.STACK_NAME }}"
        echo "Stack File: ${{ env.STACK_FILE }}"

    - name: Print Outputs
      run: |
        echo "Stack Name: ${{ steps.yaml-output.outputs.stack-name }}"
        echo "Stack File: ${{ steps.yaml-output.outputs.stack-file }}" 

    - name: Set STACK Name
        # You may pin to the exact commit or the version.
        # uses: action-pack/set-secret@4e7be4fb208cf00c083efb45a6101dd65a8eea78
      uses: action-pack/set-secret@v1
      with:
          # Secret name
          name: STACK_NAME
          # Secret value
          value: ${{env.STACK_NAME}}
          # Repository access token
          token: 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
      
    - name: Set STACK File
        # You may pin to the exact commit or the version.
        # uses: action-pack/set-secret@4e7be4fb208cf00c083efb45a6101dd65a8eea78
      uses: action-pack/set-secret@v1
      with:
          # Secret name
          name: STACK_FILE
          # Secret value
          value: ${{env.STACK_FILE}}
          # Repository access token
          token: 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
      
