name: Example Workflow

on: [push, pull_request]

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run YAML to Github Output Action
      id: yaml-output
      uses: christian-ci/action-yaml-github-output@v2
      with:
        file_path: ./cloudformation/stack-var.yml
        main_key: stackfilevar

    - name: Print Variables
      run: |
        echo "Stack Name: ${{ env.STACK_NAME }}"
        echo "Stack File: ${{ env.STACK_FILE }}"

    - name: Print Outputs
      run: |
        echo "Stack Name: ${{ steps.yaml-output.outputs.stack-name }}"
        echo "Stack File: ${{ steps.yaml-output.outputs.stack-file }}"    
