name: 'Deploy to AWS CloudFormation'

on: 
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region to deploy to'
        required: true
        default: 'us-east-1'


jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: dotnet publish --no-self-contained --runtime linux-x64 --configuration Release --output ./artifact/publish ./cloudformation/*.yml
    - name: Copy
      run: cp ./cloudformation/*.yml  ./artifact/*.yml

    - uses: actions/upload-artifact@v3
      with:
        name: cfncode
        path: ./artifact
    # Configure AWS Credential
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCESS_KEY_SECRET }}
          aws-region: ${{ github.event.inputs.region }}

    - name: Upload to S3
      run: aws s3 cp ./artifact/test-stack.yml s3://cfndemo-bucket
    # Deploy to AWS CloudFormation
    - name: Deploy to AWS CloudFormation
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
          name: harish-test-stack
          template: s3://cfndemo-bucket/test-stack.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: ""