name: Create secret variabl


jobs:
  cloudformation-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Set Secret
        # You may pin to the exact commit or the version.
        # uses: action-pack/set-secret@4e7be4fb208cf00c083efb45a6101dd65a8eea78
        uses: action-pack/set-secret@v1
        with:
          # Secret name
          name: STACK_NAME
          # Secret value
          value: testvalue123
          # Repository access token
          token: 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
